[package]
name = "hyper-body"
version = "0.1.0"
edition = "2021"

[dependencies]
hyper = { version = "1.5.0", default-features = false }
http-body-util = { version = "0.1.2", default-features = false }
tower = { version = "0.5.1", default-features = false }
